# use the official Python base image
FROM python:3.10-bookworm

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# create directory for the app user
RUN mkdir -p /home/app

# create the app user
RUN groupadd -r app && useradd -r -g app app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME && \
    mkdir $APP_HOME/staticfiles && \
    mkdir $APP_HOME/mediafiles

WORKDIR $APP_HOME

# copy project files
COPY .env $APP_HOME
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# install netcat-openbsd package
RUN apt-get update && \
    apt-get install netcat-openbsd -y && \
    chmod +x $APP_HOME/entrypoint.sh

# install dependencies
RUN python3 -m pip install --user --upgrade pip && \
    python3 -m pip install -r requirements.txt

# change to the app user
USER app

# expose the app on port 8000
EXPOSE 8000

# run entrypoint.sh
ENTRYPOINT ["/home/app/web/entrypoint.sh"]
